### ISSUE TITLE
Cant deploy contract with BigInteger

### ISSUE THREAD

**Issue by outdoteth** [mithrilcoin-io/biginteger-for-eosio#1]
Getting this error:
```1601049ms thread-0   http_plugin.cpp:405           handle_exception     ] FC Exception encountered while processing chain.push_transaction
1601049ms thread-0   http_plugin.cpp:406           handle_exception     ] Exception Details: 10 assert_exception: Assert Exception
!"unresolvable": env._ZN10BigIntegerC1Ei
    {"module":"env","export":"_ZN10BigIntegerC1Ei"}
    thread-0  wasm_interface.hpp:41 resolve
```
when i try to do ```cleos set contract myaccount111 ../mycontract```. I am only getting this error whenever i try to use the BigInteger library (simply declaring ```BigInteger foo = 4;``` causes an error).

**Comment by swapnibble** [comment]
you should feed source file to eosiocpp as the build instruction in readme.
ex) eoscpp -o <wastOutput.wast> <yourContractSrc.cpp> eos_mem_wrapper.cpp BigInteger.cpp BigIntegerAlgorithms.cpp BigIntegerUtils.cpp BigUnsigned.cpp BigUnsignedInABase.cpp
